name:                   camfort
version:                1.0
synopsis:               CamFort - Cambridge Fortran infrastructure
description:            CamFort is a tool for the analysis, transformation, verification of Fortran code.
homepage:               https://camfort.github.io
bug-reports:            https://github.com/camfort/camfort/issues
copyright:              2012-2019 University of Cambridge
author:                 Matthew Danish, Mistral Contrastin, Andrew Rice, Dominic Orchard
maintainer:             Matthew Danish
license:                Apache-2.0
license-file:           LICENSE
stability:              experimental
build-type:             Simple
category:               Language
tested-with:            GHC >= 8.6
github:                 camfort/camfort

extra-source-files:
  - tests/fixtures/Specification/Stencils/*.f
  - tests/fixtures/Specification/Units/*.f90
  - tests/fixtures/Transformation/*.f90
  - CHANGELOG.md

library:
  source-dirs: src
  build-tools:
    alex: 3.2.*
    happy: 1.19.*
  extra-libraries: flint
  other-modules: []
  exposed-modules:
    - Camfort.Analysis
    - Camfort.Analysis.Logger
    - Camfort.Analysis.Annotations
    - Camfort.Analysis.CommentAnnotator
    - Camfort.Analysis.ModFile
    - Camfort.Analysis.Simple
    - Camfort.Specification.Parser

    - Camfort.Specification.DerivedDataType
    - Camfort.Specification.DerivedDataType.Parser
    - Camfort.Specification.Stencils.Analysis
    - Camfort.Specification.Stencils.Annotation
    - Camfort.Specification.Stencils.CheckBackend
    - Camfort.Specification.Stencils.CheckFrontend
    - Camfort.Specification.Stencils.Consistency
    - Camfort.Specification.Stencils.DenotationalSemantics
    - Camfort.Specification.Stencils.InferenceBackend
    - Camfort.Specification.Stencils.InferenceFrontend
    - Camfort.Specification.Stencils.PartialOrd
    - Camfort.Specification.Stencils.Model
    - Camfort.Specification.Stencils.Syntax
    - Camfort.Specification.Stencils.Generate
    - Camfort.Specification.Stencils.Parser
    - Camfort.Specification.Stencils.Parser.Types
    - Camfort.Specification.Stencils.Synthesis
    - Camfort.Specification.Stencils

    - Camfort.Specification.Units
    - Camfort.Specification.Units.Analysis
    - Camfort.Specification.Units.Analysis.Consistent
    - Camfort.Specification.Units.Analysis.Criticals
    - Camfort.Specification.Units.Analysis.Infer
    - Camfort.Specification.Units.Annotation
    - Camfort.Specification.Units.InferenceBackend
    - Camfort.Specification.Units.InferenceBackendFlint
    - Camfort.Specification.Units.InferenceBackendSBV
    - Camfort.Specification.Units.BackendTypes
    - Camfort.Specification.Units.Environment
    - Camfort.Specification.Units.ModFile
    - Camfort.Specification.Units.Monad
    - Camfort.Specification.Units.MonadTypes
    - Camfort.Specification.Units.Parser
    - Camfort.Specification.Units.Parser.Types
    - Camfort.Specification.Units.Synthesis

    - Camfort.Specification.Hoare
    - Camfort.Specification.Hoare.Annotation
    - Camfort.Specification.Hoare.Parser
    - Camfort.Specification.Hoare.Parser.Types
    - Camfort.Specification.Hoare.Lexer
    - Camfort.Specification.Hoare.Syntax
    - Camfort.Specification.Hoare.Translate
    - Camfort.Specification.Hoare.CheckFrontend
    - Camfort.Specification.Hoare.CheckBackend

    - Camfort.Transformation.CommonBlockElim
    - Camfort.Transformation.DeadCode
    - Camfort.Transformation.EquivalenceElim

    - Camfort.Helpers
    - Camfort.Helpers.Syntax
    - Camfort.Helpers.Vec
    - Camfort.Helpers.TypeLevel
    - Camfort.Functionality
    - Camfort.Input
    - Camfort.Output
    - Camfort.Reprint

    - Language.Fortran.Model
    - Language.Fortran.Model.Singletons
    - Language.Fortran.Model.Types
    - Language.Fortran.Model.Types.Match
    - Language.Fortran.Model.Translate
    - Language.Fortran.Model.Repr
    - Language.Fortran.Model.Repr.Prim
    - Language.Fortran.Model.Vars
    - Language.Fortran.Model.Op
    - Language.Fortran.Model.Op.Eval
    - Language.Fortran.Model.Op.Core
    - Language.Fortran.Model.Op.Core.Match
    - Language.Fortran.Model.Op.Core.Core
    - Language.Fortran.Model.Op.Core.Eval
    - Language.Fortran.Model.Op.Meta
    - Language.Fortran.Model.Op.High
    - Language.Fortran.Model.Util

  dependencies:
    - base >= 4.6 && < 5
    - ghc-prim >= 0.3.1.0 && < 0.7
    - containers >= 0.5.0.0 && < 0.7
    - uniplate >= 1.6.10 && < 1.7
    - syz >= 0.2 && < 0.3
    - syb >= 0.4 && < 0.8
    - matrix >= 0.2.2 && < 0.4
    - hmatrix >= 0.20 && < 0.21
    - mtl >= 2.1 && < 2.3
    - text >= 0.11.2.3 && < 1.3
    - array >= 0.4 && < 0.6
    - directory >= 1.2 && < 1.4
    - transformers >= 0.5.5.0 && < 0.6
    - vector >= 0.1 && < 0.13
    - GenericPretty >= 1.2.2 && < 1.3
    - pretty >=1.1 && <2
    - fortran-src >= 0.4 && < 0.5
    - filepath >= 1.4 && < 1.5
    - bytestring >= 0.10 && < 0.12
    - fgl >= 5.6 && < 5.8
    - binary >= 0.8.3.0 && < 0.11
    - lattices >= 2.0.0 && < 2.1
    - sbv >= 8.0 && < 9
    - lens >= 4.15.1 && < 6
    - mmorph >= 1.0.9 && < 2
    - singletons >= 2.2 && < 3
    - template-haskell >= 2.11 && < 3
    - vinyl >= 0.6 && < 1.0
    - verifiable-expressions >= 0.6.0 && < 0.8.0
    - strict >= 0.3.2 && < 1
    - deepseq >= 1.4 && < 1.5
    - pipes >= 4.3 && < 4.4
    - parallel >= 3.2 && < 3.3

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    build-tools:
      - hspec-discover
    dependencies:
      - camfort
      - base >= 4.6 && < 5
      - containers >= 0.5.0.0 && < 0.7
      - filepath >= 1.4 && < 1.5
      - directory >= 1.2 && < 2
      - hspec >= 2.2 && < 3
      - QuickCheck >= 2.8 && < 3
      - fgl >= 5.6 && < 5.8
      - fortran-src >= 0.4 && < 0.5
      - uniplate >= 1.6.10 && < 1.7
      - mtl >= 2.1 && < 2.3
      - bytestring >= 0.10 && < 0.12
      - array >= 0.4 && < 0.6
      - hmatrix >= 0.20 && < 0.21
      - text >= 0.11.2.3 && < 1.3
      - binary >= 0.8.3.0 && < 0.11
      - lattices >= 2.0.0 && < 2.1
      - sbv >= 8.0 && < 9
      - silently >= 1.2 && < 1.3
      - temporary >= 1.2.0.4 && < 1.4
      - lens >= 4.15.1 && < 5
      - verifiable-expressions >= 0.6.0 && < 0.8.0
      - time >= 1.8 && < 1.12

executable:
  main: src/Main.hs
  other-modules: []
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  dependencies:
    - camfort
    - base >= 4.6 && < 5
    - directory >= 1.2 && < 2
    - optparse-applicative >= 0.14 && < 0.16
    - fortran-src >= 0.4 && < 0.5
