flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ../fortran-src
  extra-dep: true
extra-deps:
- fortran-src-0.2.0.1
- partial-order-0.1.2.1
- sbv-7.1
resolver: lts-8.23
system-ghc: true
