name: nix build .#image

on:
  # run after successful Nix builds (lower priority, nice caching)
  workflow_run:
    workflows: [nix build]
    types:
    - completed

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  nix-build-image:
    name: nix build .#image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: camfort
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # configured to tag the image with git commit (= `git rev-parse HEAD`)
    - run: nix build .#image

    - run: podman load < ./result

    - uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    # 2023-06-28: redhat-actions/push-to-registry doesn't let you qualify your
    # target image, so it's pretty much useless. lmao
    # https://github.com/redhat-actions/push-to-registry/issues/66
    - run: podman push localhost/camfort:$(git rev-parse HEAD) ${{ env.IMAGE_REGISTRY }}/camfort
