name: nix build

on:
  # run on every push to every branch (visibility doesn't matter)
  push:
  # don't want pull_request config, since it would run twice

jobs:
  nix-build:
    name: nix build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: camfort
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
